# Generated by Django 6.0.1 on 2026-01-15 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='answer',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='bot',
            name='response',
            field=models.CharField(max_length=255),
        ),
    ]
